apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "checkout-api.fullname" . }}
  labels:
    {{- include "checkout-api.labels" . | nindent 4 }}
data:
  greeting: {{ .Values.config.greeting | quote }}
  feature-flags: {{ .Values.config.featureFlags | quote }}
