apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-web
  namespace: practice-app
  labels:
    app: practice-web
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: practice-web
  template:
    metadata:
      labels:
        app: practice-web
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.26
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
