#!/usr/bin/env bash
# Pull the incident window out of Prometheus and render it as an ASCII chart.
#
# A PNG screenshot of Grafana would show the same thing, but a text chart is
# reviewable in a pull request, diffable, and does not rot when the cluster is
# torn down. Written to evidence/07-burn-timeline.md.
#
#   ./evidence/render-timeline.sh [START_ISO] [END_ISO]
set -euo pipefail

cd "$(dirname "$0")/.."

PROM_NS=monitoring
PROM_SVC=svc/kube-prom-stack-kube-prome-prometheus
PORT=${PORT:-9093}
OUT=evidence/07-burn-timeline.md

# Default to the last 45 minutes, which covers the whole experiment.
END=${2:-$(date -u '+%Y-%m-%dT%H:%M:%SZ')}
START=${1:-$(date -u -d '45 minutes ago' '+%Y-%m-%dT%H:%M:%SZ')}

PF_PID=""
cleanup() { [[ -n "$PF_PID" ]] && kill "$PF_PID" 2>/dev/null || true; }
trap cleanup EXIT

kubectl port-forward -n "$PROM_NS" "$PROM_SVC" "${PORT}:9090" >/dev/null 2>&1 &
PF_PID=$!
for _ in $(seq 1 40); do
  curl -sf "http://localhost:${PORT}/-/ready" >/dev/null 2>&1 && break
  sleep 0.25
done

fetch() {
  curl -sG \
    --data-urlencode "query=$1" \
    --data-urlencode "start=${START}" \
    --data-urlencode "end=${END}" \
    --data-urlencode "step=30s" \
    "http://localhost:${PORT}/api/v1/query_range"
}

fetch 'slo:availability_error:ratio_rate5m{service="slo-demo"}' > /tmp/slo-5m.json
fetch 'slo:availability_error:ratio_rate1h{service="slo-demo"}' > /tmp/slo-1h.json
fetch 'slo:availability_burn_rate:1h{service="slo-demo"}'       > /tmp/slo-burn.json

python3 - "$START" "$END" <<'PY' > "$OUT"
import json, sys, datetime

start, end = sys.argv[1], sys.argv[2]

def load(path):
    with open(path) as f:
        d = json.load(f)
    r = d["data"]["result"]
    if not r:
        return {}
    return {int(float(t)): float(v) for t, v in r[0]["values"]}

s5   = load("/tmp/slo-5m.json")
s1h  = load("/tmp/slo-1h.json")
burn = load("/tmp/slo-burn.json")

ts = sorted(set(s5) | set(s1h) | set(burn))

PAGE_THRESHOLD = 0.072   # 14.4 x 0.005
WIDTH = 44
SCALE_MAX = 0.40         # chart tops out at 40% error ratio

def bar(v):
    if v is None:
        return " " * WIDTH
    n = min(WIDTH, max(0, round(v / SCALE_MAX * WIDTH)))
    mark = round(PAGE_THRESHOLD / SCALE_MAX * WIDTH)
    cells = []
    for i in range(WIDTH):
        if i < n:
            cells.append("#")
        elif i == mark:
            cells.append("|")
        else:
            cells.append(" ")
    return "".join(cells)

def pct(v):
    return "     -  " if v is None else f"{v*100:6.2f}%"

def bx(v):
    return "    -  " if v is None else f"{v:6.2f}x"

print("# Evidence 07 — Error budget burn, rendered from Prometheus")
print()
print(f"Window: `{start}` -> `{end}`, step 30s.")
print()
print("Generated by `evidence/render-timeline.sh` straight from the Prometheus")
print("`query_range` API — these are the same series the burn-rate alerts evaluate.")
print()
print("The `|` in each bar marks the **7.2% fast-burn page threshold**")
print("(14.4 x the 0.5% error budget). The chart is scaled to 40% full width.")
print()
print("```")
print(f"{'time (UTC)':>10}  {'5m SLI':>7} {'1h SLI':>7} {'burn':>7}  5m error ratio  0%{' '*(WIDTH-14)}40%")
print("-" * (10 + 2 + 7 + 1 + 7 + 1 + 7 + 2 + WIDTH))
for t in ts:
    hhmm = datetime.datetime.utcfromtimestamp(t).strftime("%H:%M:%S")
    v5 = s5.get(t)
    print(f"{hhmm:>10}  {pct(v5)} {pct(s1h.get(t))} {bx(burn.get(t))}  {bar(v5)}")
print("```")
print()

# Narrate the transitions the chart shows.
above = [t for t in ts if (s5.get(t) or 0) > PAGE_THRESHOLD]
if above:
    f = datetime.datetime.utcfromtimestamp(above[0]).strftime("%H:%M:%SZ")
    l = datetime.datetime.utcfromtimestamp(above[-1]).strftime("%H:%M:%SZ")
    print(f"- 5m window first crossed the 7.2% page threshold at **{f}**")
    print(f"- 5m window last above the page threshold at **{l}**")
peak = max((v for v in burn.values()), default=None)
if peak:
    print(f"- peak 1h burn rate: **{peak:.2f}x** (sustainable is 1.0x)")
PY

echo "Wrote $OUT"
head -30 "$OUT"
